name: Feature request
description: Request a feature
title: '[Feature] '
labels:
  - enhancement
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide a detailed description of the feature.
      placeholder: Adds unicorns
    validations:
      required: true
  - type: textarea
    id: other-solutions
    attributes:
      label: Alternative solutions
      description: What are some alternatives to adding this feature?
